# 配置tomcat端口号
server:
  port: 9000

# 配置rabbitmq
spring:
  rabbitmq:
    host: 81.70.165.182   #mq地址
    port: 22        #端口
    username: root   #登录账号
    password: ncl@1234   #登录密码
    virtual-host: /   #虚拟机

